package org.microraiden.demo;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.microraiden.demo.MicroRaiden;

public class MicroRaidenTest {
    @Test
    public void test() {
        MicroRaiden classUnderTest = new MicroRaiden();
        assert(true);
    }
}
